import C from '../../images/c.png';
const skillsData = [
  {
    id: 1,
    img: C,
    skill: 'C',
  },
  {
    id: 2,
    img: 'https://cdn-icons-png.flaticon.com/512/6132/6132222.png',
    skill: 'C++',
    attribute: 'https://www.flaticon.com/free-icons/coding',
    attributeTitle: 'coding icons',
    attributeText: 'Coding icons created by Freepik - Flaticon',
  },
  {
    id: 3,
    img: 'https://cdn-icons-png.flaticon.com/512/6132/6132221.png',
    skill: 'C#',
    attribute: 'https://www.flaticon.com/free-icons/c-sharp',
    attributeTitle: 'c sharp icons',
    attributeText: 'C sharp icons created by Freepik - Flaticon',
  },
  {
    id: 4,
    img: 'https://cdn-icons-png.flaticon.com/512/5968/5968350.png',
    skill: 'Python',
    attribute: 'https://www.flaticon.com/free-icons/python',
    attributeTitle: 'python icons',
    attributeText: 'Python icons created by Freepik - Flaticon',
  },
  {
    id: 5,
    img: 'https://cdn-icons-png.flaticon.com/512/5968/5968282.png',
    skill: 'Java',
    attribute: 'https://www.flaticon.com/free-icons/java',
    attributeTitle: 'java icons',
    attributeText: 'Java icons created by Freepik - Flaticon',
  },
  {
    id: 6,
    img: 'https://cdn-icons-png.flaticon.com/512/5968/5968292.png',
    skill: 'JavaScript',
    attribute: 'https://www.flaticon.com/free-icons/javascript',
    attributeTitle: 'javascript icons',
    attributeText: 'Javascript icons created by Freepik - Flaticon',
  },
  {
    id: 7,
    img: 'https://cdn-icons-png.flaticon.com/512/3334/3334886.png',
    skill: 'React',
    attribute: 'https://www.flaticon.com/free-icons/react',
    attributeTitle: 'react icons',
    attributeText: 'React icons created by Pixel perfect - Flaticon',
  },
  {
    id: 8,
    img: 'https://cdn-icons-png.flaticon.com/512/5968/5968267.png',
    skill: 'HTML',
    attribute: 'https://www.flaticon.com/free-icons/html-5',
    attributeTitle: 'html 5 icons',
    attributeText: 'Html 5 icons created by Freepik - Flaticon',
  },
  {
    id: 9,
    img: 'https://cdn-icons-png.flaticon.com/512/5968/5968242.png',
    skill: 'CSS',
    attribute: 'https://www.flaticon.com/free-icons/css-3',
    attributeTitle: 'css 3 icons',
    attributeText: 'Css 3 icons created by Freepik - Flaticon',
  },
  {
    id: 10,
    img: 'https://cdn-icons-png.flaticon.com/512/5968/5968672.png',
    skill: 'Bootstrap',
    attribute: 'https://www.flaticon.com/free-icons/bootstrap',
    attributeTitle: 'bootstrap icons',
    attributeText: 'Bootstrap icons created by Freepik - Flaticon',
  },
  {
    id: 11,
    img: 'https://cdn-icons-png.flaticon.com/512/2784/2784065.png',
    skill: 'Agile',
    attribute: 'https://www.flaticon.com/free-icons/agile',
    attributeTitle: 'agile icons',
    attributeText: 'Agile icons created by Freepik - Flaticon',
  },
  {
    id: 12,
    img: 'https://cdn-icons-png.flaticon.com/512/226/226770.png',
    skill: 'Android',
    attribute: 'https://www.flaticon.com/free-icons/android',
    attributeTitle: 'android icons',
    attributeText: 'Android icons created by Freepik - Flaticon',
  },
  {
    id: 13,
    img: 'https://img.icons8.com/color/480/000000/android-studio--v3.png',
    skill: 'Android Studio',
    attribute: 'https://icons8.com/icon/04OFrkjznvcd/android-studio',
    attributeTitle: 'android studio icon',
    attributeText: 'Android Studio icon by Icons8',
  },
  {
    id: 14,
    img: 'https://img.icons8.com/color/480/000000/visual-studio-code-2019.png',
    skill: 'Visual Studio Code',
    attribute: 'https://icons8.com/icon/9OGIyU8hrxW5/visual-studio-code-2019',
    attributeTitle: 'visual studio code icon',
    attributeText: 'Visual Studio Code 2019 icon by Icons8',
  },
  {
    id: 15,
    img: 'https://img.icons8.com/color/480/000000/visual-studio--v2.png',
    skill: 'Visual Studio',
    attribute: 'https://icons8.com/icon/y7WGoWNuIWac/visual-studio',
    attributeTitle: 'visual studio icon',
    attributeText: 'Visual Studio icon by Icons8',
  },
  {
    id: 16,
    img: 'https://cdn-icons-png.flaticon.com/512/3291/3291695.png',
    skill: 'Github',
    attribute: 'https://www.flaticon.com/free-icons/github',
    attributeTitle: 'github icons',
    attributeText: 'Github icons created by riajulislam - Flaticon',
  },
  {
    id: 17,
    img: 'https://cdn-icons-png.flaticon.com/512/2772/2772128.png',
    skill: 'SQL',
    attribute: 'https://www.flaticon.com/free-icons/sql',
    attributeTitle: 'sql icons',
    attributeText: 'Sql icons created by Pixel perfect - Flaticon',
  },
  {
    id: 18,
    img: 'https://img.icons8.com/color/480/000000/windows-10.png',
    skill: 'Windows OS',
    attribute: 'https://icons8.com/icon/108792/windows-10',
    attributeTitle: 'windows icon',
    attributeText: 'Windows 10 icon by Icons8',
  },
  {
    id: 19,
    img: 'https://img.icons8.com/color/480/000000/mac-logo.png',
    skill: 'Mac OS',
    attribute: 'https://icons8.com/icon/122959/mac-logo',
    attributeTitle: 'mac icon',
    attributeText: 'Mac Logo icon by Icons8',
  },
  {
    id: 20,
    img: 'https://img.icons8.com/color/480/000000/microsoft-office-2019.png',
    skill: 'Microsoft Office',
    attribute: 'https://icons8.com/icon/6kZdxe7t8OL1/microsoft-office-2019',
    attributeTitle: 'microsoft office icon',
    attributeText: 'Microsoft Office 2019 icon by Icons',
  },
  {
    id: 21,
    img: 'https://img.icons8.com/color/480/000000/google-drive--v1.png',
    skill: 'Google Drive',
    attribute: 'https://icons8.com/icon/13630/google-drive',
    attributeTitle: 'google drive icon',
    attributeText: 'Google Drive icon by Icons8',
  },
];
export default skillsData;